##### To fill null values

In [38]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [39]:
data = pd.read_csv("food_coded.csv")

In [40]:
data.shape

(125, 61)

In [41]:
data.head(5)

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

##### Shows data type of each column

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

In [43]:
data.isnull().sum()

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         26
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

In [44]:
x = data.fillna(method = "bfill",axis=0)
print(x.head())
#"bfill"/"ffill"  fills backward and forward data

     GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4       2          1               430           3.0           315.0
1  3.654       1          1               610           3.0           420.0
2    3.3       1          1               720           4.0           420.0
3    3.2       1          1               430           3.0           420.0
4    3.5       1          1               720           2.0           420.0

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort
1       2       chocolate, chips, ice cream        Stress, bored, anger
2       2   frozen yogurt, pizza, fast food             stress, sadness
3       2  Pizza, Mac and cheese, ice cream                     Boredom
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0
1                         1.0  ...   1.0     1.0          2             725.0
2                         1.0  ...   1.0     2.0          5            1165.0
3                         2.0  ...   1.0     2.0          5             725.0
4                         1.0  ...   1.0     1.0          4             940.0

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315
1              690  Basketball            4         2              900
2              500         none           5         1              900
3              690     Softball           3         1             1315
4              500     Softball           4         2              760

                     weight
0                       187
1                       155
2  I'm not answering this.
3             Not sure, 240
4                       190

[5 rows x 61 columns]

C:\Users\Riddhi\AppData\Local\Temp\ipykernel_10700\3247470827.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  x = data.fillna(method = "bfill",axis=0)

##### To fill categorial values

In [45]:
for i in data.select_dtypes(include="object").columns:
    data[i].fillna(data[i].mode()[0],inplace=True)

C:\Users\Riddhi\AppData\Local\Temp\ipykernel_10700\2008568610.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[i].fillna(data[i].mode()[0],inplace=True)

In [46]:
data.isnull().sum() 
#only numerical values have remained

GPA                  0
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports          0
veggies_day          0
vitamins             0
waffle_calories      0
weight               0
Length: 61, dtype: int64

In [47]:
from sklearn.impute import SimpleImputer

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           125 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  125 non-null    object
 8   comfort_food_reasons          125 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  125 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                125 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             125 non-null    object
 25  fav_cuisine                   125 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                125 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  125 non-null    object
 35  ideal_diet                    125 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           125 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             125 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   125 non-null    object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        125 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

In [49]:
data.select_dtypes(include="float64").columns

Index(['calories_day', 'calories_scone', 'comfort_food_reasons_coded', 'cook',
       'cuisine', 'drink', 'employment', 'exercise', 'father_education',
       'fav_food', 'income', 'life_rewarding', 'marital_status',
       'mother_education', 'on_off_campus', 'persian_food',
       'self_perception_weight', 'soup', 'sports', 'tortilla_calories'],
      dtype='object')

In [50]:
#fills float missing value by mean by scikit-learn
si = SimpleImputer(strategy="mean")
ar = si.fit_transform(data[['calories_day', 'calories_scone', 'comfort_food_reasons_coded', 'cook',
       'cuisine', 'drink', 'employment', 'exercise', 'father_education',
       'fav_food', 'income', 'life_rewarding', 'marital_status',
       'mother_education', 'on_off_campus', 'persian_food',
       'self_perception_weight', 'soup', 'sports', 'tortilla_calories']])

In [51]:
pd.DataFrame(ar,columns=['calories_day', 'calories_scone', 'comfort_food_reasons_coded', 'cook',
       'cuisine', 'drink', 'employment', 'exercise', 'father_education',
       'fav_food', 'income', 'life_rewarding', 'marital_status',
       'mother_education', 'on_off_campus', 'persian_food',
       'self_perception_weight', 'soup', 'sports', 'tortilla_calories'])

,calories_day,calories_scone,comfort_food_reasons_coded,cook,cuisine,drink,employment,exercise,father_education,fav_food,income,life_rewarding,marital_status,mother_education,on_off_campus,persian_food,self_perception_weight,soup,sports,tortilla_calories
0,3.028302,315.0,9.000000,2.000000,1.388889,1.0,3.0,1.0,5.0,1.0,5.0,1.0,1.0,1.0,1.0,5.0,3.0,1.0,1.000000,1165.0
1,3.000000,420.0,1.000000,3.000000,1.000000,2.0,2.0,1.0,2.0,1.0,4.0,1.0,2.0,4.0,1.0,4.0,3.0,1.0,1.000000,725.0
2,4.000000,420.0,1.000000,1.000000,3.000000,1.0,3.0,2.0,2.0,3.0,6.0,7.0,2.0,2.0,2.0,5.0,6.0,1.0,2.000000,1165.0
3,3.000000,420.0,2.000000,2.000000,2.000000,2.0,3.0,3.0,2.0,1.0,6.0,2.0,2.0,4.0,1.0,5.0,5.0,1.0,2.000000,725.0
4,2.000000,420.0,1.000000,1.000000,2.000000,2.0,2.0,1.0,4.0,3.0,6.0,1.0,1.0,5.0,1.0,2.0,4.0,1.0,1.000000,940.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,4.000000,420.0,2.698113,3.000000,1.000000,2.0,1.0,2.0,4.0,1.0,4.0,7.0,1.0,3.0,3.0,3.0,4.0,1.0,1.000000,940.0
121,2.000000,315.0,2.698113,3.000000,1.388889,1.0,3.0,2.0,5.0,1.0,2.0,7.0,1.0,2.0,1.0,1.0,4.0,1.0,1.390244,940.0
122,3.028302,420.0,2.698113,3.000000,1.388889,1.0,3.0,2.0,5.0,1.0,2.0,10.0,1.0,1.0,1.0,5.0,4.0,1.0,2.000000,580.0
123,4.000000,420.0,2.698113,3.000000,1.000000,2.0,2.0,1.0,3.0,3.0,4.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.000000,940.0
124,3.028302,315.0,2.698113,2.786885,3.000000,1.0,2.0,2.0,4.0,1.0,5.0,5.0,2.0,3.0,1.0,2.0,3.0,1.0,2.000000,725.0

##### Label Encoding

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
df = pd.DataFrame({"name":["Riddhi","Samruddhi","Ruchika","Samiksha"]})

In [54]:
le = LabelEncoder()
df["en_name"] = le.fit_transform(df["name"])

In [55]:
df

        name  en_name
0     Riddhi        0
1  Samruddhi        3
2    Ruchika        1
3   Samiksha        2

##### Ordinal Encoding

In [56]:
dframe = pd.DataFrame({"Size":["s","m","l","xl","s","m","l","xl","s","xl","m"]})
dframe

   Size
0     s
1     m
2     l
3    xl
4     s
5     m
6     l
7    xl
8     s
9    xl
10    m

In [57]:
from sklearn.preprocessing import OrdinalEncoder

In [58]:
ord_data = [["s","m","l","xl"]]

In [59]:
oe = OrdinalEncoder(categories=ord_data)
oe.fit(dframe[["Size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [62]:
dframe["en_size"] = oe.transform(dframe[["Size"]])
dframe

   Size  en_size
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7    xl      3.0
8     s      0.0
9    xl      3.0
10    m      1.0

##### Ordinal Encoding through map

In [63]:
ord_data1 = {"s":0,"m":1,"l":2,"xl":3}

In [65]:
dframe["en_size1"] = dframe["Size"].map(ord_data1)
dframe

   Size  en_size  en_size1
0     s      0.0         0
1     m      1.0         1
2     l      2.0         2
3    xl      3.0         3
4     s      0.0         0
5     m      1.0         1
6     l      2.0         2
7    xl      3.0         3
8     s      0.0         0
9    xl      3.0         3
10    m      1.0         1